<?php
/**
 * Generated by: FrameBro.
 * Date: 06/22/17
 * Time: 07:06 pm
 */

namespace App\Migrations;


use App\Core\Migrations\Migrations;
use App\Core\Migrations\Table;
use App\Models\Format;

class CreateMovieMigration extends Migrations
{

    public function up()
    {
        $this->create('formats', function(Table $t) {
            $t->incremental('fid');
            $t->char("name", 20)->unique();
        });

        $this->create('movies', function(Table $t) {
            $t->incremental('mid')->unsigned();
            $t->char('title', 50)->index();
            $t->char('format', 20)->index();
            $t->integer('length');
            $t->integer("release");
            $t->decimal("rating", 5, 1)->null();
            $t->timestamps();

        });
        $format = new Format();
        $format->insert([
            ["name" => "VHS"],
            ["name" => "DVD"],
            ["name" => "Streaming"]
        ]);

        $this->update('movies', function (Table $t) {
            $t->foreign('formats', 'name', "format");
        });
    }

    public function down()
    {
        $this->drop('formats');
        $this->drop('movies');
    }
}